### PR TITLE
Expose different OpenCL platforms as different SYCL platforms

### LINKED ISSUE #1631: get_pointer_type fails when there's multiple OpenCL platforms
**Bug summary**

Looks like `select_usm_device_index(ctx, backend)` returns the first device with the given backend from a context. In turn, this means that `select_usm_allocator(ctx)` will, in this case, always return the allocator for the first device, even if more than one device is available. This confuses `sycl::get_pointer_type` and, in turn, `sycl::free`.

This happens to work ok with CUDA and HIP, since `hipPointerGetAttributes` etc don't care about a specific context, but looks like the Intel USM API is more picky, and `clGetMemAllocInfoINTEL` returns `CL_MEM_TYPE_UNKNOWN_INTEL` when a wrong context is used.

**To Reproduce**

Need a platform with two OpenCL devices:

```cpp
#include <sycl/sycl.hpp>

using T = char;

std::ostream& operator<<(std::ostream& out, const sycl::usm::alloc &e) {
    switch(e) {
        case sycl::usm::alloc::host:
            out << "host"; break;
        case sycl::usm::alloc::device:
            out << "device"; break;
        case sycl::usm::alloc::shared:
            out << "shared"; break;
        case sycl::usm::alloc::unknown:
            out << "unknown"; break;
    }
    return out;
}

int main() {
  for (const auto &dev :
       sycl::device::get_devices(sycl::info::device_type::gpu)) {
    std::cout << "Running on " << dev.get_info<sycl::info::device::name>()
              << std::endl;
    sycl::queue q{dev, {sycl::property::queue::in_order()}};

    std::cout << "  Malloc device..." << std::endl;
    char *arr_d = sycl::malloc_device<T>(123, q);
    std::cout << "    Got pointer of type " << sycl::get_pointer_type(arr_d, q.get_context()) << std::endl;

    std::cout << "  Free device..." << std::endl;
    sycl::free(arr_d, q);
    std::cout << "  Done!" << std::endl;
  }
}
```

```console
$ acpp -O0 -g --acpp-targets=generic test_usm.cpp && ACPP_VISIBILITY_MASK=opencl ./a.out 
Running on Intel(R) Arc(TM) A770 Graphics
  Malloc device...
    Got pointer of type device
  Free device...
  Done!
Running on Intel(R) UHD Graphics 770
  Malloc device...
    Got pointer of type unknown
  Free device...
[AdaptiveCpp Error] from /home/aland/AdaptiveCpp/src/runtime/ocl/ocl_allocator.cpp:72 @ raw_free(): ocl_allocator: USM memory free() failed (error code = CL:-30)
  Done!
============== hipSYCL error report ============== 
hipSYCL has caught the following unhandled asynchronous errors: 

   0. from /home/aland/AdaptiveCpp/src/runtime/ocl/ocl_allocator.cpp:72 @ raw_free(): ocl_allocator: USM memory free() failed (error code = CL:-30)
The application will now be terminated.
terminate called without an active exception
Aborted (core dumped)
```

**Expected behavior**


```console
$ acpp -O0 -g --acpp-targets=generic test_usm.cpp && ACPP_VISIBILITY_MASK=opencl ./a.out 
Running on Intel(R) Arc(TM) A770 Graphics
  Malloc device...
    Got pointer of type device
  Free device...
  Done!
Running on Intel(R) UHD Graphics 770
  Malloc device...
    Got pointer of type device
  Free device...
  Done!
```

**Describe your setup**

```
acpp [AdaptiveCpp compilation driver], Copyright (C) 2018-2024 Aksel Alpay and the AdaptiveCpp project
  AdaptiveCpp version: 24.06.0+git.026e7219.20241205.branch.develop
  Installation root: /home/aland/local
  Plugin LLVM version: 18, can accelerate CPU: True
  Available runtime backends:
     librt-backend-cuda.so
     librt-backend-omp.so
     librt-backend-ze.so
     librt-backend-hip.so
     librt-backend-ocl.so


Full configuration [can be overridden using environment variables or command line arguments]:
    version-major: 24
    version-minor: 06
    version-patch: 0
    version-suffix: +git.026e7219.20241205.branch.develop
    plugin-llvm-version-major: 18
    plugin-with-cpu-acceleration: true
    default-clang: /usr/lib/llvm-18/bin/clang++
    default-targets: generic
    default-cpu-cxx: /usr/bin/clang++-18
    default-rocm-path: /opt/rocm
    default-use-bootstrap-mode: false
    default-is-dryrun: false
    default-use-accelerated-cpu: true
    default-clang-include-path: /usr/lib/llvm-18/lib/clang/18/include/..
    default-sequential-link-line: -L/usr/lib/x86_64-linux-gnu -lboost_context -lboost_fiber -Wl,-rpath=/usr/lib/x86_64-linux-gnu
    default-sequential-cxx-flags: -I/usr/include -D_ENABLE_EXTENDED_ALIGNED_STORAGE
    default-omp-link-line: -L/usr/lib/x86_64-linux-gnu -lboost_context -lboost_fiber -Wl,-rpath=/usr/lib/x86_64-linux-gnu -fopenmp
    default-omp-cxx-flags: -I/usr/include -fopenmp -D_ENABLE_EXTENDED_ALIGNED_STORAGE
    default-is-explicit-multipass: false
    default-save-temps: false
    default-rocm-link-line: -Wl,-rpath=$HIPSYCL_ROCM_PATH/lib -Wl,-rpath=$HIPSYCL_ROCM_PATH/hip/lib -L/opt/rocm/lib -L/opt/rocm/hip/lib -lamdhip64
    default-rocm-cxx-flags: -isystem $HIPSYCL_PATH/include/AdaptiveCpp/hipSYCL/std/hiplike -isystem /usr/lib/llvm-18/lib/clang/18/include/.. -U__FLOAT128__ -U__SIZEOF_FLOAT128__ -I$HIPSYCL_ROCM_PATH/include -I$HIPSYCL_ROCM_PATH/include --rocm-device-lib-path=$HIPSYCL_ROCM_PATH/amdgcn/bitcode --rocm-path=$HIPSYCL_ROCM_PATH -fhip-new-launch-api -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -D__HIP_ROCclr__
    default-nvcxx: (unconfigured)
    default-cuda-path: /usr/local/cuda
    default-cuda-link-line: -Wl,-rpath=$HIPSYCL_CUDA_LIB_PATH -L$HIPSYCL_CUDA_LIB_PATH -lcudart
    default-cuda-cxx-flags: -U__FLOAT128__ -U__SIZEOF_FLOAT128__ -isystem $HIPSYCL_PATH/include/AdaptiveCpp/hipSYCL/std/hiplike
```

**Additional information**

Creating a context with a single device and using it to construct a queue fixes this specific example:

```
    sycl::context ctx{dev};                                                                                                                                                                                                                                                                                                         
    sycl::queue q{ctx, dev, {sycl::property::queue::in_order()}};
```

However, multi-device contexts are allowed in general, so this is not a good fix.

### PR DESCRIPTION
**Pull request by illuhad**
PR #1590 has changed semantics of the default-constructed queue, in that it now constructs a context of all of the devices in the queue device's platform.
This causes a problem in OpenCL, since it then can happen that we generate SYCL contexts (by default!) that span multiple OpenCL platforms, which is then renders substantial parts of the SYCL API dysfunctional.

This PR attempts to address this by putting different OpenCL platforms in different SYCL platforms.

Hopefully fixes #1631 

@al42and Can you give this a try?

Draft because I've only done very limited testing.

### CODE REVIEW

File: include/hipSYCL/sycl/platform.hpp [hunk 1]
```diff
@@ -148,7 +168,10 @@ HIPSYCL_SPECIALIZE_GET_INFO(platform, version)
 HIPSYCL_SPECIALIZE_GET_INFO(platform, name)
 {
   rt::backend_id b = _platform.get_backend();
-  return _requires_runtime.get()->backends().get(b)->get_name();
+  std::string platform_name =
+      _requires_runtime.get()->backends().get(b)->get_name();
+  platform_name +=
+      " (platform " + std::to_string(_platform.get_platform()) + ")";
```
Comment (al42and) [inline include/hipSYCL/sycl/platform.hpp:174]:
```suggestion
      " (platform " + std::to_string(_platform.get_platform()) + ")";
      return platform_name;
```

**Review by al42and — APPROVED** [review]
Missing `return` aside, seems to work! :+1:
