### PR TITLE
Make sure that local memory for CPU backend is suitably aligned

### LINKED ISSUE #536: Segmentation fault in example code if compiler optimizations are turned on
**Bug summary**
Segmentation fault in nbody example if optimizations are turned on.

**To Reproduce**
I set up hipSYCL on Ubuntu 21.04 with:
```
sudo apt install clang llvm libboost-context-dev libboost-fiber-dev cmake
git clone --recurse-submodules github:illuhad/hipSYCL
cd hipSYCL
mkdir build installation
cd build
cmake -DCMAKE_INSTALL_PREFIX=../installation ..
make install
cd ../examples/bruteforce_nbody/
```

Then I compile and run the example:
```
../../installation/bin/syclcc bruteforce_nbody.cpp
./a.out
```
It works (in the sense that all CPU cores are at 100% and some content is written to `output.txt`).

If I turn on the compiler optimizations, I get a segmentation fault:
```
../../installation/bin/syclcc -O2 bruteforce_nbody.cpp
./a.out
```
returns:
```
Writing output...
[1]    107879 segmentation fault (core dumped)  ./a.out
```

**Expected behavior**
The example code should run both with and without compiler optimizations.

**Describe your setup**
* I am on the hipSYCL `develop` branch, checkout `395920dd606133a98c831092508e2002e8ceab1d`.

*  clang version
```bash
$ clang --version
Ubuntu clang version 12.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

* How you have compiled your application and which arguments you have passed to `syclcc`. In particular, which backends and hardware you have compiled for.
See above. I am using the CPU backend only.

**Optional additional diagnostic information**

Output with debug level = 3:

```
[;32m[hipSYCL Info] [0mdata_region: constructed with page table dimensions 1 1 1
[;32m[hipSYCL Info] [0mdata_region: constructed with page table dimensions 1 1 1
[;32m[hipSYCL Info] [0mdata_region: constructed with page table dimensions 1 1 1
[;32m[hipSYCL Info] [0mbackend_loader: Searching path for backend libs: '"/home/philipp/git/hipSYCL/installation/bin/../lib/hipSYCL"'
[;32m[hipSYCL Info] [0mbackend_loader: Successfully opened plugin: "/home/philipp/git/hipSYCL/installation/bin/../lib/hipSYCL/librt-backend-omp.so" for backend 'omp'
[;32m[hipSYCL Info] [0mRegistering backend: 'omp'...
[;32m[hipSYCL Info] [0mmulti_queue_executor: Spawned for backend OpenMP with configuration: 
[;32m[hipSYCL Info] [0m  device 0: 
[;32m[hipSYCL Info] [0m    memcpy lane: 0
[;32m[hipSYCL Info] [0m    kernel lane: 1
[;32m[hipSYCL Info] [0mDiscovered devices from backend 'OpenMP': 
[;32m[hipSYCL Info] [0m  device 0: 
[;32m[hipSYCL Info] [0m    vendor: the hipSYCL project
[;32m[hipSYCL Info] [0m    name: hipSYCL OpenMP host device
[;32m[hipSYCL Info] [0mdag_manager: DAG manager is alive!
[;32m[hipSYCL Info] [0mruntime: ******* rt launch initiated ********
[;32m[hipSYCL Info] [0mqueue: Constructed queue with node group id 1
[;32m[hipSYCL Info] [0mdag_manager: Checking DAG flush opportunity...
[;32m[hipSYCL Info] [0mdag_manager: Submitting asynchronous flush...
[;32m[hipSYCL Info] [0mdag_manager [async]: Flushing!
[;32m[hipSYCL Info] [0mdag_manager: Checking DAG flush opportunity...
[;32m[hipSYCL Info] [0mdag_manager: Submitting asynchronous flush...
Writing output...
[;32m[hipSYCL Info] [0maccessor [host]: Initializing host access
[;32m[hipSYCL Info] [0mdag_builder: DAG contains operation: kernel: ZZ4mainENKUlRN7hipsycl4sycl7handlerEE_clES2_EUlNS0_7nd_itemILi1EEEE_
   MEM_REQ: R device {0, 0, 0}+{1, 1, 40000} #16
   MEM_REQ: Discard W device {0, 0, 0}+{1, 1, 40000} #16
[;32m[hipSYCL Info] [0m    --> requires: MEM_REQ: R device {0, 0, 0}+{1, 1, 40000} #16
[;32m[hipSYCL Info] [0m    --> requires: MEM_REQ: Discard W device {0, 0, 0}+{1, 1, 40000} #16
[;32m[hipSYCL Info] [0mdag_builder: DAG contains operation: kernel: ZZ4mainENKUlRN7hipsycl4sycl7handlerEE0_clES2_EUlNS0_7nd_itemILi1EEEE_
   MEM_REQ: RW device {0, 0, 0}+{1, 1, 40000} #16
   MEM_REQ: RW device {0, 0, 0}+{1, 1, 40000} #16
   MEM_REQ: R device {0, 0, 0}+{1, 1, 40000} #16
[;32m[hipSYCL Info] [0m    --> requires: MEM_REQ: RW device {0, 0, 0}+{1, 1, 40000} #16
[;32m[hipSYCL Info] [0m    --> requires: MEM_REQ: RW device {0, 0, 0}+{1, 1, 40000} #16
[;32m[hipSYCL Info] [0m    --> requires: MEM_REQ: R device {0, 0, 0}+{1, 1, 40000} #16
[;32m[hipSYCL Info] [0mdag_builder: DAG contains operation: MEM_REQ: R device {0, 0, 0}+{1, 1, 40000} #16
[;32m[hipSYCL Info] [0mdag_builder: DAG contains operation: MEM_REQ: Discard W device {0, 0, 0}+{1, 1, 40000} #16
[;32m[hipSYCL Info] [0mdag_builder: DAG contains operation: MEM_REQ: RW device {0, 0, 0}+{1, 1, 40000} #16
[;32m[hipSYCL Info] [0m    --> requires: kernel: ZZ4mainENKUlRN7hipsycl4sycl7handlerEE_clES2_EUlNS0_7nd_itemILi1EEEE_
   MEM_REQ: R device {0, 0, 0}+{1, 1, 40000} #16
   MEM_REQ: Discard W device {0, 0, 0}+{1, 1, 40000} #16
[;32m[hipSYCL Info] [0mdag_builder: DAG contains operation: MEM_REQ: RW device {0, 0, 0}+{1, 1, 40000} #16
[;32m[hipSYCL Info] [0mdag_builder: DAG contains operation: MEM_REQ: R device {0, 0, 0}+{1, 1, 40000} #16
[;32m[hipSYCL Info] [0m    --> requires: kernel: ZZ4mainENKUlRN7hipsycl4sycl7handlerEE_clES2_EUlNS0_7nd_itemILi1EEEE_
   MEM_REQ: R device {0, 0, 0}+{1, 1, 40000} #16
   MEM_REQ: Discard W device {0, 0, 0}+{1, 1, 40000} #16
[;32m[hipSYCL Info] [0mdag_manager [async]: Releasing dead users of data region 0x55d1a8d995f0
[;32m[hipSYCL Info] [0mdag_manager [async]: Releasing dead users of data region 0x55d1a8d9aac0
[;32m[hipSYCL Info] [0mdag_manager [async]: Releasing dead users of data region 0x55d1a8d995f0
[;32m[hipSYCL Info] [0maccessor [host]: forcing DAG flush for host access...[;32m[hipSYCL Info] [0m
[;32m[hipSYCL Info] [0mdag_manager: Submitting asynchronous flush...
[;32m[hipSYCL Info] [0mdag_manager: waiting for async worker...
dag_manager [async]: Releasing dead users of data region 0x55d1a8d9a8c0
[;32m[hipSYCL Info] [0mdag_manager [async]: Releasing dead users of data region 0x55d1a8d9aac0
[;32m[hipSYCL Info] [0mdag_manager [async]: Submitting node to direct scheduler!
[;32m[hipSYCL Info] [0mdag_direct_scheduler: Setting device data pointer of requirement node MEM_REQ: R device {0, 0, 0}+{1, 1, 40000} #16 to 0x7f48911e4010
[;32m[hipSYCL Info] [0mdag_direct_scheduler: Setting device data pointer of requirement node MEM_REQ: Discard W device {0, 0, 0}+{1, 1, 40000} #16 to 0x7f488f888010
[;32m[hipSYCL Info] [0mmulti_queue_executor: Processing node 0x55d1a8d9ef30 with 0 non-virtual requirement(s) and 2 direct requirement(s).
[;32m[hipSYCL Info] [0mmulti_queue_executor: Dispatching to lane 1: kernel: ZZ4mainENKUlRN7hipsycl4sycl7handlerEE_clES2_EUlNS0_7nd_itemILi1EEEE_
   MEM_REQ: R device {0, 0, 0}+{1, 1, 40000} #16
   MEM_REQ: Discard W device {0, 0, 0}+{1, 1, 40000} #16
[;32m[hipSYCL Info] [0momp_queue: Submitting kernel...
[;32m[hipSYCL Info] [0momp_queue: Inserting event into queue...
[;32m[hipSYCL Info] [0momp_queue [async]: Invoking kernel!
[;32m[hipSYCL Info] [0mbuffer_memory_requirement: Attempting to initialize embedded pointers for requirement [;32m[hipSYCL Info] [0m0x55d1a8da3db0dag_manager [async]: Submitting node to direct scheduler!

[;32m[hipSYCL Info] [0mIdentified embedded pointer with uid 8818481019922013887-4906125864742910683 in kernel blob, setting to 0x7f48911e4010
[;32m[hipSYCL Info] [0mbuffer_memory_requirement: Attempting to initialize embedded pointers for requirement 0x55d1a8da4020
[;32m[hipSYCL Info] [0mIdentified embedded pointer with uid 9322807215336928825-7860750003526659291 in kernel blob, setting to 0x7f488f888010
[;32m[hipSYCL Info] [0mdag_direct_scheduler: Setting device data pointer of requirement node MEM_REQ: RW device {0, 0, 0}+{1, 1, 40000} #16 to 0x7f48911e4010
[;32m[hipSYCL Info] [0mdag_direct_scheduler: Setting device data pointer of requirement node MEM_REQ: RW device {0, 0, 0}+{1, 1, 40000} #16 to 0x7f4891128010
[;32m[hipSYCL Info] [0mdag_direct_scheduler: Setting device data pointer of requirement node MEM_REQ: R device {0, 0, 0}+{1, 1, 40000} #16 to 0x7f488f888010
[;32m[hipSYCL Info] [0mmulti_queue_executor: Processing node 0x55d1a8d9f6c0 with 1 non-virtual requirement(s) and 3 direct requirement(s).
[;32m[hipSYCL Info] [0m --> (Skipping same-lane synchronization with node: 0x55d1a8d9ef30)
[;32m[hipSYCL Info] [0mmulti_queue_executor: Dispatching to lane 1: kernel: ZZ4mainENKUlRN7hipsycl4sycl7handlerEE0_clES2_EUlNS0_7nd_itemILi1EEEE_
   MEM_REQ: RW device {0, 0, 0}+{1, 1, 40000} #16
   MEM_REQ: RW device {0, 0, 0}+{1, 1, 40000} #16
   MEM_REQ: R device {0, 0, 0}+{1, 1, 40000} #16
[;32m[hipSYCL Info] [0momp_queue: Submitting kernel...
[;32m[hipSYCL Info] [0momp_queue: Inserting event into queue...
[;32m[hipSYCL Info] [0mdag_manager [async]: Flushing!
[;32m[hipSYCL Info] [0mdag_builder: DAG contains operation: MEM_REQ: R host_buffer {0, 0, 0}+{1, 1, 40000} #16
[;32m[hipSYCL Info] [0m    --> requires: kernel: ZZ4mainENKUlRN7hipsycl4sycl7handlerEE0_clES2_EUlNS0_7nd_itemILi1EEEE_
   MEM_REQ: RW device {0, 0, 0}+{1, 1, 40000} #16
   MEM_REQ: RW device {0, 0, 0}+{1, 1, 40000} #16
   MEM_REQ: R device {0, 0, 0}+{1, 1, 40000} #16
[;32m[hipSYCL Info] [0mdag_manager [async]: Submitting node to direct scheduler!
[;32m[hipSYCL Info] [0mdag_direct_scheduler: Setting device data pointer of requirement node MEM_REQ: R host_buffer {0, 0, 0}+{1, 1, 40000} #16 to 0x7f48911e4010
[;32m[hipSYCL Info] [0mdag_manager [async]: Nothing to do
[;32m[hipSYCL Info] [0mdag_manager: Checking DAG flush opportunity...
[;32m[hipSYCL Info] [0mdag_manager: Submitting asynchronous flush...
[;32m[hipSYCL Info] [0maccessor [host]: Waiting for completion of host access...
[;32m[hipSYCL Info] [0mdag_manager [async]: Nothing to do
```
 

I am new to SYCL and hipSYCL in particular. Any help is very much appreciated.

### PR DESCRIPTION
**Pull request by illuhad**
Make sure that local memory for CPU backend is suitably aligned for any data type. Resolves #536

This is a hotfix, the CPU local memory allocator should probably be refactored and unified with the local memory used for the group algorithms.

### CODE REVIEW

File: include/hipSYCL/sycl/libkernel/detail/local_memory_allocator.hpp [hunk 1]
```diff
@@ -157,7 +158,10 @@ class host_local_memory
   // for more local memory we go to the heap.
   static constexpr size_t _max_static_local_mem_size = 1024*32;
   inline static char* _local_mem;
-  inline static std::array<char, _max_static_local_mem_size> _static_local_mem;
+  
+  alignas(alignof(std::max_align_t)) inline static char _static_local_mem
```
Comment (fodinabor) [inline include/hipSYCL/sycl/libkernel/detail/local_memory_allocator.hpp:162]: Any specific reason to not use `std::aligned_storage_t<_max_static_local_mem_size, alignof(std::max_align_t)> _static_local_mem{};`?

Comment (illuhad) [reply include/hipSYCL/sycl/libkernel/detail/local_memory_allocator.hpp:162]: I think `aligned_storage_t` does not define which underlying data type it uses apart from using a POD type. Using a char array directly here probably avoids some reinterpret pointer casts later on.

**Comment by illuhad** [comment]
@hipSYCL-ci-bot test
