### PR TITLE
[Omp] set global_mem_size to physical mem size if available

### LINKED ISSUE #1573: global_mem_size == 2^64-1
**Bug summary**
get_device().get_info<sycl::info::device::global_mem_size>() returns 18446744073709551615 for cpu device.

**To Reproduce**
e.g.
```cpp
spdlog::info("Device: {}", Globals::Queue.get_device().get_info<sycl::info::device::name>());
auto global_mem = Globals::Queue.get_device().get_info<sycl::info::device::global_mem_size>();
spdlog::info("Global memory: {} MB", global_mem / 1024 / 1024);
```

**Expected behavior**
Intel dpc++ returns "Global memory: 128700 MB" as expected for the available host memory for device "Device: AMD Ryzen 9 5950X 16-Core Processor", while in case of SYCL the byte count from above ("Global memory: 17592186044415 MB") for "Device: hipSYCL OpenMP host device". This happens for both the OMP and generic workflow.

When checking with the GPU backend (via generic workflow), everything works as expected with AdaptiveCPP.
```
[2024-09-27 14:12:13.153] [logger_rank0] [info] Device: NVIDIA GeForce RTX 3090
[2024-09-27 14:12:17.371] [logger_rank0] [info] Global memory: 24145 MB
```

**Describe your setup**
Installed from git commit ~ 1 month ago.

### PR DESCRIPTION
**Pull request by tdavidcl**
This PR set the value of global_mem_size in the OpenMP device properties to be the physical memory size.

 Closes #1573

TODOs: 

- [x] Windows case
- [ ] testing ??? @illuhad What approach do you I think I should use to test this in CI if possible ?

### CODE REVIEW

File: src/runtime/omp/omp_phys_mem.cpp [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+}
+return value;
+}
+
+// Linux/BSD implementation:
+#elif (defined(linux) || defined(__linux__) || defined(__linux))                                   \
+|| (defined(__DragonFly__) || defined(__FreeBSD__) || defined(__NetBSD__)                      \
+    || defined(__OpenBSD__))
+
+#include <sys/sysinfo.h>
```
Comment (illuhad) [inline src/runtime/omp/omp_phys_mem.cpp]: Maybe the following is a better heuristic?
```c++
#ifdef __has_include
  #if __has_include(<sys/sysinfo.h>)
   ...
  #endif
#endif
```
or are there cases where the header exists, but doesn't provide the functionality?

File: src/runtime/omp/omp_phys_mem.cpp [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+ */
+// SPDX-License-Identifier: BSD-2-Clause
+#include "hipSYCL/runtime/omp/omp_phys_mem.hpp"
+
+// Mac OSX implementation:
+#if defined(__MACH__)
+#include <sys/sysctl.h>
+#include <sys/types.h>
+
+std::optional<std::size_t> hipsycl::rt::getPhysicalMemory() {
```
Comment (illuhad) [inline src/runtime/omp/omp_phys_mem.cpp]: We generally only use camelCase for LLVM compiler code to conform to LLVM conventions. So maybe better to use snake_case here?

File: src/runtime/omp/omp_hardware_manager.cpp [hunk 3]
```diff
@@ -247,7 +257,7 @@ omp_hardware_context::get_property(device_uint_property prop) const {
     return 1; // TODO
     break;
   case device_uint_property::global_mem_size:
-    return std::numeric_limits<std::size_t>::max(); // TODO
+    return phys_mem_or_max(); // TODO
```
Comment (illuhad) [inline src/runtime/omp/omp_hardware_manager.cpp]: I think the TODO is there because of the placeholder value that we used to return, so we can get rid of that comment with this PR :)

File: include/hipSYCL/runtime/omp/omp_phys_mem.hpp [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+ * @brief Get the amount of physical memory (RAM) available on the system, in
+ * bytes.
+ *
+ * @return The amount of physical memory available, or std::nullopt if the
+ * information cannot be retrieved.
+ *
+ * @details This function is implemented for Mac OS X and Linux. Other platforms
+ * will return std::nullopt.
+ */
+std::optional<std::size_t> getPhysicalMemory();
```
Comment (illuhad) [inline include/hipSYCL/runtime/omp/omp_phys_mem.hpp]: Is there a benefit to this being a free function? Would it perhaps make more sense to have this be a private member function of `omp_hardware_context`, or even just defined in an anonymous namespace in `omp_hardware_manager.cpp`?

I suppose the question boils down to whether there is some need to know the physical memory size outside of that class. Hm....

File: include/hipSYCL/runtime/omp/omp_phys_mem.hpp [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+ * This file is part of AdaptiveCpp, an implementation of SYCL and C++ standard
+ * parallelism for CPUs and GPUs.
+ *
+ * Copyright The AdaptiveCpp Contributors
+ *
+ * AdaptiveCpp is released under the BSD 2-Clause "Simplified" License.
+ * See file LICENSE in the project root for full license details.
+ */
+// SPDX-License-Identifier: BSD-2-Clause
+#ifndef HIPSYCL_OMP_PHYS_MEM_HPP
```
Comment (illuhad) [inline include/hipSYCL/runtime/omp/omp_phys_mem.hpp]:
```suggestion
#ifndef ACPP_OMP_PHYS_MEM_HPP
```

File: include/hipSYCL/runtime/omp/omp_phys_mem.hpp [hunk 6]
```diff
@@ -0,0 +1,34 @@
...
+#define HIPSYCL_OMP_PHYS_MEM_HPP
```
Comment (illuhad) [inline include/hipSYCL/runtime/omp/omp_phys_mem.hpp]:
```suggestion
#define ACPP_OMP_PHYS_MEM_HPP
```

File: src/runtime/omp/omp_phys_mem.cpp [hunk 7]
```diff
@@ -0,0 +1,58 @@
...
+
+int mib[]     = {CTL_HW, HW_MEMSIZE};
+int64_t value = 0;
+size_t length = sizeof(value);
+
+if (-1 == sysctl(mib, 2, &value, &length, NULL, 0)) {
+    return std::nullopt;
+}
+return value;
```
Comment (illuhad) [inline src/runtime/omp/omp_phys_mem.cpp]: Can you please fix indentation for this function?

**Review by illuhad — COMMENTED** [review]
Thanks! I don't see how we could really test this in CI... Perhaps check that it returns a value greater than 0 and smaller than some unrealistic large number, like 100 Petabyte or so...

File: include/hipSYCL/runtime/omp/omp_phys_mem.hpp (hunk 4 above)
Comment (tdavidcl) [reply include/hipSYCL/runtime/omp/omp_phys_mem.hpp]: yeah since there is some #ifdef like switches I wanted to hide it in a separate file to have a clean interface.

File: src/runtime/omp/omp_phys_mem.cpp (hunk 1 above)
Comment (tdavidcl) [reply src/runtime/omp/omp_phys_mem.cpp]: I move the linux case in the else and guard the return by `#if __has_include(<sys/sysinfo.h>)`

**Review by illuhad — APPROVED** [review]
Thanks!
